### ISSUE TITLE
Error on pipeline.predict

### ISSUE THREAD

**Issue by Sash0check** [aimclub/FEDOT.Web#104]
AttributeError: 'OneHotEncoder' object has no attribute 'sparse_output'

It appears on every pipline evaluation.
![Screenshot_18](https://user-images.githubusercontent.com/16399597/219060575-976efcb3-8d6c-4057-8a52-3284c71d2a90.png)

**Comment by nicl-nno** [comment]
Ну выглядит как расхождения в версиях fedot-а и мб sklearn, использованных при создании историй и в текущей версии. А это можно воспроизвести тестом на гитхабе?

**Comment by Sash0check** [comment]
Создавал венв на 3.10 - закрываю issue
