### ISSUE TITLE
ModuleNotFoundError: No module named 'golem'

### ISSUE THREAD

**Issue by v1docq** [aimclub/FEDOT.Web#112]
When trying to visualize the optimization history using a file [https://github.com/aimclub/FEDOT.Web/blob/master/scripts/upload_custom_history.py](url)  error occurs with importing the golem library.
![image](https://user-images.githubusercontent.com/48867680/233045267-f194c769-c98d-48ee-8fbc-fd06f9775159.png)
![image](https://user-images.githubusercontent.com/48867680/233045434-b3cada29-b066-4d3d-8bdb-9dafd2d50c39.png)

**Comment by nicl-nno** [comment]
[ind_history.zip](https://github.com/aimclub/FEDOT.Web/files/11271946/ind_history.zip)
