### ISSUE TITLE
Error while initializing database by init_db.py

### ISSUE THREAD

**Issue by hemangjoshi37a** [aimclub/FEDOT.Web#96]
Error while running: `python init_db.py`

```
Traceback (most recent call last):
  File "init_db.py", line 16, in <module>
    db = client.get_default_database()
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1948, in get_default_database
    raise ConfigurationError("No default database name defined or provided.")
pymongo.errors.ConfigurationError: No default database name defined or provided.
```
https://hjlabs.in

**Comment by MorrisNein** [comment]
> Error while running: python init_db.py
> 
>

> Traceback (most recent call last):
>   File "init_db.py", line 16, in <module>
>     db = client.get_default_database()
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1948, in get_default_database
>     raise ConfigurationError("No default database name defined or provided.")
> pymongo.errors.ConfigurationError: No default database name defined or provided.
> 
> https://hjlabs.in

Hello, @hemangjoshi37a!
Please, firstly, make sure that you have environmental variables set up according to the build instruction.

The provided error points out that you don't have `MONGO_CONN_STRING="mongodb://127.0.0.1:27017/test_db?compressors=zlib"` as an environmental variable.

Then, before running the script, make sure you have started your Mongo database. The following ways are possible:

1. Windows OS:
 
  - `cd C:\Program Files\MongoDB\Server\3.2\bin`
  - `mongod`

2. Linux

  - `sudo service mongod start`

**Comment by MorrisNein** [comment]
> How to set anything as an environment variable?

This depends on what OS you use.

**Comment by hemangjoshi37a** [comment]
> > How to set anything as an environment variable?
> 
> This depends on OS that you use.
> 
> Windows power shell:
> 
> `$env:VARNAME = value`
> 
> Windows cmd:
> 
> `export varname=value`
> 
> Linux bash:
> 
> `$ export VAR="my value"`
> 
> 

Thanks for the solution.👍
